os:
    - linux

language:
    - cpp

compiler:
    - g++

addons:
    apt: 
        sources:
            - ubuntu-toolchain-r-test

        packages:
            - python-yaml
            - g++-4.8 
            - libc6-i386

install:
    - sudo ln -sf /usr/bin/gcc-4.8 /usr/bin/gcc
    - sudo ln -sf /usr/bin/g++-4.8 /usr/bin/g++
    - sudo pip install cpp-coveralls
    - sudo add-apt-repository --yes ppa:beineri/opt-qt56
    - sudo apt-get update -qq
    - travis_retry sudo apt-get install -qq qt-latest

script:
    - QTDIR="/opt/qt55"
    - PATH="$QTDIR/bin:$PATH"
    - qt55-env.sh 

    - qmake -v
    - qmake Virtualio.pro CONFIG+=debug "QT += testlib"

    - g++ --version
    - make

    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - sleep 3

    - ./Virtualio --test

after_success:
    - cd src
    - exclude_regexs=('.*/moc_.*' '.*\.moc$' '.*_automoc\..*' '.*/ui_.*' '.*/qrc_.*' '.*CMake.*' '.*/tests/.*')
    - arguments=()
    - for regex in "${exclude_regexs[@]}"; do arguments+=(--exclude-pattern "$regex"); done
    - coveralls --gcov /usr/bin/gcov-4.8 "${arguments[@]}"